apiVersion: v1
kind: Service
metadata:
  name: littlebaby
  labels:
    app: littlebaby
spec:
  type: ClusterIP
  selector:
    app: littlebaby
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
