packages:
  - .
  - extensions/*

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "acpx"
  - "axios"
  - "basic-ftp"
  - "hono"
  - "littlebaby"
  - "protobufjs"
  - "@buape/carbon"
  - "vite"
  - "@cloudflare/workers-types"
  - "@hono/node-server"
  - "@mariozechner/*"
  - "@typescript/native-preview*"
  - "@types/node"
  - "@rolldown/*"
  - "axios@1.15.0"
  - "discord-api-types"
  - "rolldown"

onlyBuiltDependencies:
  - "@discordjs/opus"
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@tloncorp/api"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - esbuild
  - protobufjs

ignoredBuiltDependencies:
  - koffi
