#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${LITTLEBABY_INSTALL_E2E_IMAGE:-littlebaby-install-e2e:local}"
INSTALL_URL="${LITTLEBABY_INSTALL_URL:-https://littlebaby.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
LITTLEBABY_E2E_MODELS="${LITTLEBABY_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e LITTLEBABY_INSTALL_URL="$INSTALL_URL" \
  -e LITTLEBABY_INSTALL_TAG="${LITTLEBABY_INSTALL_TAG:-latest}" \
  -e LITTLEBABY_E2E_MODELS="$LITTLEBABY_E2E_MODELS" \
  -e LITTLEBABY_INSTALL_E2E_PREVIOUS="${LITTLEBABY_INSTALL_E2E_PREVIOUS:-}" \
  -e LITTLEBABY_INSTALL_E2E_SKIP_PREVIOUS="${LITTLEBABY_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e LITTLEBABY_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
