export const browserCoreExamples = [
  "littlebaby browser status",
  "littlebaby browser start",
  "littlebaby browser stop",
  "littlebaby browser tabs",
  "littlebaby browser open https://example.com",
  "littlebaby browser focus abcd1234",
  "littlebaby browser close abcd1234",
  "littlebaby browser screenshot",
  "littlebaby browser screenshot --full-page",
  "littlebaby browser screenshot --ref 12",
  "littlebaby browser snapshot",
  "littlebaby browser snapshot --format aria --limit 200",
  "littlebaby browser snapshot --efficient",
  "littlebaby browser snapshot --labels",
];

export const browserActionExamples = [
  "littlebaby browser navigate https://example.com",
  "littlebaby browser resize 1280 720",
  "littlebaby browser click 12 --double",
  'littlebaby browser type 23 "hello" --submit',
  "littlebaby browser press Enter",
  "littlebaby browser hover 44",
  "littlebaby browser drag 10 11",
  "littlebaby browser select 9 OptionA OptionB",
  "littlebaby browser upload /tmp/littlebaby/uploads/file.pdf",
  'littlebaby browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "littlebaby browser dialog --accept",
  'littlebaby browser wait --text "Done"',
  "littlebaby browser evaluate --fn '(el) => el.textContent' --ref 7",
  "littlebaby browser console --level error",
  "littlebaby browser pdf",
];
